 WHERE
 (Status_Transport LIKE '%' + {{ ui.ontable11.filters.Status_Transport ?? "" }} + '%' OR {{ ui.ontable11.filters.Status_Transport ?? "" }} = '')
AND (TransmissionTimestamp LIKE '%' + {{ ui.ontable11.filters.TransmissionTimestamp ?? "" }} + '%' OR {{ ui.ontable11.filters.TransmissionTimestamp ?? "" }} = '')
AND (Voyage LIKE '%' + {{ ui.ontable11.filters.Voyage ?? "" }} + '%' OR {{ ui.ontable11.filters.Voyage ?? "" }} = '')
AND (ContainerSize LIKE '%' + {{ ui.ontable11.filters.ContainerSize ?? "" }} + '%' OR {{ ui.ontable11.filters.ContainerSize ?? "" }} = '')
AND (Broker LIKE '%' + {{ ui.ontable11.filters.Broker ?? "" }} + '%' OR {{ ui.ontable11.filters.Broker ?? "" }} = '')
AND (Carrier LIKE '%' + {{ ui.ontable11.filters.Carrier ?? "" }} + '%' OR {{ ui.ontable11.filters.Carrier ?? "" }} = '')
AND (Vessel LIKE '%' + {{ ui.ontable11.filters.Vessel ?? "" }} + '%' OR {{ ui.ontable11.filters.Vessel ?? "" }} = '')
AND (PortOfDischarge_Lima LIKE '%' + {{ ui.ontable11.filters.PortOfDischarge_Lima ?? "" }} + '%' OR {{ ui.ontable11.filters.PortOfDischarge_Lima ?? "" }} = '')
AND (ETA_PortOfDischarge LIKE '%' + {{ ui.ontable11.filters.ETA_PortOfDischarge ?? "" }} + '%' OR {{ ui.ontable11.filters.ETA_PortOfDischarge ?? "" }} = '')
AND (PackingMethod LIKE '%' + {{ ui.ontable11.filters.PackingMethod ?? "" }} + '%' OR {{ ui.ontable11.filters.PackingMethod ?? "" }} = '')
AND (TotalWeight LIKE '%' + {{ ui.ontable11.filters.TotalWeight ?? "" }} + '%' OR {{ ui.ontable11.filters.TotalWeight ?? "" }} = '')
AND (AdvertFlag LIKE '%' + {{ ui.ontable11.filters.AdvertFlag ?? "" }} + '%' OR {{ ui.ontable11.filters.AdvertFlag ?? "" }} = '')
AND (RealAdvertFlag LIKE '%' + {{ ui.ontable11.filters.RealAdvertFlag ?? "" }} + '%' OR {{ ui.ontable11.filters.RealAdvertFlag ?? "" }} = '')
AND (EarliestAdvertDate LIKE '%' + {{ ui.ontable11.filters.EarliestAdvertDate ?? "" }} + '%' OR {{ ui.ontable11.filters.EarliestAdvertDate ?? "" }} = '')
AND (EarliestRealAdvertDate LIKE '%' + {{ ui.ontable11.filters.EarliestRealAdvertDate ?? "" }} + '%' OR {{ ui.ontable11.filters.EarliestRealAdvertDate ?? "" }} = '')
AND (todo LIKE '%' + {{ ui.ontable11.filters.todo ?? "" }} + '%' OR {{ ui.ontable11.filters.todo ?? "" }} = '')
AND (last_eventID LIKE '%' + {{ ui.ontable11.filters.last_eventID ?? "" }} + '%' OR {{ ui.ontable11.filters.last_eventID ?? "" }} = '')
AND (PortOfLoading_Lima LIKE '%' + {{ ui.ontable11.filters.PortOfLoading_Lima ?? "" }} + '%' OR {{ ui.ontable11.filters.PortOfLoading_Lima ?? "" }} = '')
AND (ETD_PortOfLoading LIKE '%' + {{ ui.ontable11.filters.ETD_PortOfLoading ?? "" }} + '%' OR {{ ui.ontable11.filters.ETD_PortOfLoading ?? "" }} = '')
AND (ETA_Terminal_Inland LIKE '%' + {{ ui.ontable11.filters.ETA_Terminal_Inland ?? "" }} + '%' OR {{ ui.ontable11.filters.ETA_Terminal_Inland ?? "" }} = '')
AND (DeliveryAddress LIKE '%' + {{ ui.ontable11.filters.DeliveryAddress ?? "" }} + '%' OR {{ ui.ontable11.filters.DeliveryAddress ?? "" }} = '')
AND (ETA_DeliveryAddress LIKE '%' + {{ ui.ontable11.filters.ETA_DeliveryAddress ?? "" }} + '%' OR {{ ui.ontable11.filters.ETA_DeliveryAddress ?? "" }} = '')
AND (Transport_Mode_Terminal LIKE '%' + {{ ui.ontable11.filters.Transport_Mode_Terminal ?? "" }} + '%' OR {{ ui.ontable11.filters.Transport_Mode_Terminal ?? "" }} = '')
AND (Transport_Mode_final_DeliveryAddress LIKE '%' + {{ ui.ontable11.filters.Transport_Mode_final_DeliveryAddress ?? "" }} + '%' OR {{ ui.ontable11.filters.Transport_Mode_final_DeliveryAddress ?? "" }} = '')
AND (ATA_DeliveryAddress LIKE '%' + {{ ui.ontable11.filters.ATA_DeliveryAddress ?? "" }} + '%' OR {{ ui.ontable11.filters.ATA_DeliveryAddress ?? "" }} = '')
AND (transport_Dispo_ID LIKE '%' + {{ ui.ontable11.filters.transport_Dispo_ID ?? "" }} + '%' OR {{ ui.ontable11.filters.transport_Dispo_ID ?? "" }} = '')
AND (Condition LIKE '%' + {{ ui.ontable11.filters.Condition ?? "" }} + '%' OR {{ ui.ontable11.filters.Condition ?? "" }} = '')
AND (into_CW1 LIKE '%' + {{ ui.ontable11.filters.into_CW1 ?? "" }} + '%' OR {{ ui.ontable11.filters.into_CW1 ?? "" }} = '')
AND (to_Customer LIKE '%' + {{ ui.ontable11.filters.to_Customer ?? "" }} + '%' OR {{ ui.ontable11.filters.to_Customer ?? "" }} = '')
AND (to_Transporter LIKE '%' + {{ ui.ontable11.filters.to_Transporter ?? "" }} + '%' OR {{ ui.ontable11.filters.to_Transporter ?? "" }} = '')
AND (DropOff_Terminal LIKE '%' + {{ ui.ontable11.filters.DropOff_Terminal ?? "" }} + '%' OR {{ ui.ontable11.filters.DropOff_Terminal ?? "" }} = '')
AND (Terminal_PortOfDischarge LIKE '%' + {{ ui.ontable11.filters.Terminal_PortOfDischarge ?? "" }} + '%' OR {{ ui.ontable11.filters.Terminal_PortOfDischarge ?? "" }} = '')
AND (ATA_Terminal_Inland LIKE '%' + {{ ui.ontable11.filters.ATA_Terminal_Inland ?? "" }} + '%' OR {{ ui.ontable11.filters.ATA_Terminal_Inland ?? "" }} = '')
AND (ATD_Terminal_Inland LIKE '%' + {{ ui.ontable11.filters.ATD_Terminal_Inland ?? "" }} + '%' OR {{ ui.ontable11.filters.ATD_Terminal_Inland ?? "" }} = '')
AND (ETA_Seaport LIKE '%' + {{ ui.ontable11.filters.ETA_Seaport ?? "" }} + '%' OR {{ ui.ontable11.filters.ETA_Seaport ?? "" }} = '')
AND (final_date_delivery_address LIKE '%' + {{ ui.ontable11.filters.final_date_delivery_address ?? "" }} + '%' OR {{ ui.ontable11.filters.final_date_delivery_address ?? "" }} = '')
AND (ctv_booking_id LIKE '%' + {{ ui.ontable11.filters.ctv_booking_id ?? "" }} + '%' OR {{ ui.ontable11.filters.ctv_booking_id ?? "" }} = '')
AND (CTV_ETA_PortOfDischarge LIKE '%' + {{ ui.ontable11.filters.CTV_ETA_PortOfDischarge ?? "" }} + '%' OR {{ ui.ontable11.filters.CTV_ETA_PortOfDischarge ?? "" }} = '')
AND (PortOfDischarge_UNLOCO LIKE '%' + {{ ui.ontable11.filters.PortOfDischarge_UNLOCO ?? "" }} + '%' OR {{ ui.ontable11.filters.PortOfDischarge_UNLOCO ?? "" }} = '')
AND (PortOfLoading_UNLOCO LIKE '%' + {{ ui.ontable11.filters.PortOfLoading_UNLOCO ?? "" }} + '%' OR {{ ui.ontable11.filters.PortOfLoading_UNLOCO ?? "" }} = '')
AND (ATA_DropOff_Terminal LIKE '%' + {{ ui.ontable11.filters.ATA_DropOff_Terminal ?? "" }} + '%' OR {{ ui.ontable11.filters.ATA_DropOff_Terminal ?? "" }} = '')
AND (DeliveryAddress_CTV LIKE '%' + {{ ui.ontable11.filters.DeliveryAddress_CTV ?? "" }} + '%' OR {{ ui.ontable11.filters.DeliveryAddress_CTV ?? "" }} = '')
AND (PortOfDischarge_UNLOCO_CTV LIKE '%' + {{ ui.ontable11.filters.PortOfDischarge_UNLOCO_CTV ?? "" }} + '%' OR {{ ui.ontable11.filters.PortOfDischarge_UNLOCO_CTV ?? "" }} = '')
AND (Carrier_CTV LIKE '%' + {{ ui.ontable11.filters.Carrier_CTV ?? "" }} + '%' OR {{ ui.ontable11.filters.Carrier_CTV ?? "" }} = '')
AND (customs_document_type LIKE '%' + {{ ui.ontable11.filters.customs_document_type ?? "" }} + '%' OR {{ ui.ontable11.filters.customs_document_type ?? "" }} = '')
AND (Terminal_Inland_CTV LIKE '%' + {{ ui.ontable11.filters.Terminal_Inland_CTV ?? "" }} + '%' OR {{ ui.ontable11.filters.Terminal_Inland_CTV ?? "" }} = '')
AND (ETD_Pickup_PortOfDischarge LIKE '%' + {{ ui.ontable11.filters.ETD_Pickup_PortOfDischarge ?? "" }} + '%' OR {{ ui.ontable11.filters.ETD_Pickup_PortOfDischarge ?? "" }} = '')
AND (pinState LIKE '%' + {{ ui.ontable11.filters.pinState ?? "" }} + '%' OR {{ ui.ontable11.filters.pinState ?? "" }} = '')
AND (nationalTransportState LIKE '%' + {{ ui.ontable11.filters.nationalTransportState ?? "" }} + '%' OR {{ ui.ontable11.filters.nationalTransportState ?? "" }} = '')
AND (finalDeliveryState LIKE '%' + {{ ui.ontable11.filters.finalDeliveryState ?? "" }} + '%' OR {{ ui.ontable11.filters.finalDeliveryState ?? "" }} = '')
AND (emptyReturnState LIKE '%' + {{ ui.ontable11.filters.emptyReturnState ?? "" }} + '%' OR {{ ui.ontable11.filters.emptyReturnState ?? "" }} = '')
AND (DeliveryInfo_send_to_CTV LIKE '%' + {{ ui.ontable11.filters.DeliveryInfo_send_to_CTV ?? "" }} + '%' OR {{ ui.ontable11.filters.DeliveryInfo_send_to_CTV ?? "" }} = '')
AND ([new] LIKE '%' + {{ ui.ontable11.filters.new ?? "" }} + '%' OR {{ ui.ontable11.filters.new ?? "" }} = '')
AND (Terminal_Inland_CundA LIKE '%' + {{ ui.ontable11.filters.Terminal_Inland_CundA ?? "" }} + '%' OR {{ ui.ontable11.filters.Terminal_Inland_CundA ?? "" }} = '')
AND (Direct_Truck LIKE '%' + {{ ui.ontable11.filters.Direct_Truck ?? "" }} + '%' OR {{ ui.ontable11.filters.Direct_Truck ?? "" }} = '')
AND (EventType LIKE '%' + {{ ui.ontable11.filters.EventType ?? "" }} + '%' OR {{ ui.ontable11.filters.EventType ?? "" }} = '')
AND (Transport_To_Terminal LIKE '%' + {{ ui.ontable11.filters.Transport_To_Terminal ?? "" }} + '%' OR {{ ui.ontable11.filters.Transport_To_Terminal ?? "" }} = '')
AND (Transport_Document_Number LIKE '%' + {{ ui.ontable11.filters.Transport_Document_Number ?? "" }} + '%' OR {{ ui.ontable11.filters.Transport_Document_Number ?? "" }} = '')
AND (Seal_Number LIKE '%' + {{ ui.ontable11.filters.Seal_Number ?? "" }} + '%' OR {{ ui.ontable11.filters.Seal_Number ?? "" }} = '')
AND (ETA_Deliveryadress_CTV LIKE '%' + {{ ui.ontable11.filters.ETA_Deliveryadress_CTV ?? "" }} + '%' OR {{ ui.ontable11.filters.ETA_Deliveryadress_CTV ?? "" }} = '')
AND (tm.Wert LIKE '%' + {{ ui.ontable11.filters.MBL_No ?? "" }} + '%' OR {{ ui.ontable11.filters.MBL_No  ?? "" }} = '')
AND (tm2.Wert LIKE '%' + {{ ui.ontable11.filters.Container_No ?? "" }} + '%' OR {{ ui.ontable11.filters.Container_No ?? "" }} = '')


 ORDER BY
d.TransmissionTimestamp


OFFSET @Offset ROWS
FETCH NEXT @PageSize ROWS ONLY;