INSERT INTO dbo.Transport_Dispo_History (
    CustomerID,
    MBL_ID,
    ContainerID,
    MBL_Number,
    Container_Number,
    Status,
    [Timestamp],
    [User],
    direction,
    Relation,
    Interface,
    Transport_Dispo_ID,
    ContainerSize,
    Carrier,
    Vessel,
    Pincode,
    DropOff_Terminal,
    DropOff_Terminal_TIR,
    ETA_DeliveryAddress,
    Remarks,
    DeliveryAddress,
    ATA_Terminal_Inland,
    Containerverfuegbarkeit,
    Transport_Mode_final_DeliveryAddress,
    Direct_Truck,
    to_Transporter,
    TransmissionTimestamp,
    Tabelle
)
VALUES (
    {{ ui.form9.value.CustomerID ? "'" + ui.form9.value.CustomerID + "'" : "'UNKNOWN'" }},
    {{ ui.form9.value.MBL_ID ?? 0 }},
    {{ ui.form9.value.ContainerID ?? 0 }},
    {{ ui.form9.value.MBL_No ? "'" + ui.form9.value.MBL_No + "'" : "'UNKNOWN'" }},
    {{ ui.form9.value.Container_No ? "'" + ui.form9.value.Container_No + "'" : "'UNKNOWN'" }},
    {{ ui.form9.value.Status_Dispo ? "'" + ui.form9.value.Status_Dispo + "'" : "'transport'" }},
    '{{ moment().utcOffset(0, true).toISOString() }}',
    {{ steps.getAuditPayload.data.user ? "'" + steps.getAuditPayload.data.user + "'" : "'SYSTEM'" }},
    'INPUT',
    'Clone',
    'UI',
    {{ ui.form9.value.transport_Dispo_ID ?? 0 }},
    {{ ui.form9.value.ContainerSize ? "'" + ui.form9.value.ContainerSize + "'" : "NULL" }},
    {{ ui.form9.value.Carrier ? "'" + ui.form9.value.Carrier + "'" : "NULL" }},
    {{ ui.form9.value.Vessel ? "'" + ui.form9.value.Vessel + "'" : "NULL" }},
    {{ ui.form9.value.Pincode ? "'" + ui.form9.value.Pincode + "'" : "''" }},
    {{ ui.form9.value.DropOff_Terminal ? "'" + ui.form9.value.DropOff_Terminal + "'" : "''" }},
    {{ ui.form9.value.DropOff_Terminal_TIR ? "'" + ui.form9.value.DropOff_Terminal_TIR + "'" : "''" }},
    {{ ui.form9.value.ETA_DeliveryAddress ? "'" + moment(ui.form9.value.ETA_DeliveryAddress).toISOString() + "'" : "NULL" }},
    {{ ui.form9.value.Remarks ? "'" + ui.form9.value.Remarks + "'" : "''" }},
    {{ ui.form9.value.DeliveryAddress ? "'" + ui.form9.value.DeliveryAddress + "'" : "''" }},
    {{ ui.form9.value.ATA_Terminal_Inland ? "'" + moment(ui.form9.value.ATA_Terminal_Inland).toISOString() + "'" : "NULL" }},
    {{ ui.form9.value.Containerverfuegbarkeit ? "'" + moment(ui.form9.value.Containerverfuegbarkeit).toISOString() + "'" : "NULL" }},
    {{ ui.form9.value.Transport_Mode_final_DeliveryAddress ? "'" + ui.form9.value.Transport_Mode_final_DeliveryAddress + "'" : "''" }},
    {{ ui.form9.value.Direct_Truck ? "'" + ui.form9.value.Direct_Truck + "'" : "''" }},
    {{ ui.form9.value.to_Transporter ? "'" + ui.form9.value.to_Transporter + "'" : "0" }},
    '{{ moment().utcOffset(0, true).toISOString() }}',
    'Transport_Clone'
);
