INSERT INTO dbo.Transport_Dispo_History (
    CustomerID,
    MBL_ID,
    ContainerID,
    MBL_Number,
    Container_Number,
    Status,
    [Timestamp],
    [User],
    direction,
    Relation,
    Interface,
    Transport_Dispo_ID,
    ContainerSize,
    Carrier,
    Vessel,
    Pincode,
    DropOff_Terminal,
    DropOff_Terminal_TIR,
    ETA_DeliveryAddress,
    Remarks,
    DeliveryAddress,
    ATA_Terminal_Inland,
    Containerverfuegbarkeit,
    Transport_Mode_final_DeliveryAddress,
    Direct_Truck,
    to_Transporter,
    TransmissionTimestamp,
    Tabelle
)
VALUES (
    {{ ui.form3.value.CustomerID ?? 'UNKNOWN' }},
    {{ ui.form3.value.MBL_ID ?? 0 }},
    {{ ui.form3.value.ContainerID ?? 0 }},
    {{ ui.form3.value.MBL_No ?? 'UNKNOWN' }},
    {{ ui.form3.value.Container_No ?? 'UNKNOWN' }},
    {{ ui.form3.value.Status_Dispo ?? 'transport' }},
    {{ moment().utcOffset(0, true).toISOString() }},
    {{ steps.getAuditPayload.data.user }},
    'INPUT',
    'Clone',
    'UI',
    {{ ui.form3.value.transport_Dispo_ID ?? 0 }},
    {{ ui.form3.value.ContainerSize ?? null }},
    {{ ui.form3.value.Carrier ?? null }},
    {{ ui.form3.value.Vessel ?? null }},
    {{ ui.form3.value.Pincode ?? '' }},
    {{ ui.form3.value.DropOff_Terminal ?? '' }},
    {{ ui.form3.value.DropOff_Terminal_TIR ?? '' }},
    {{ ui.form3.value.ETA_DeliveryAddress ? moment(ui.form3.value.ETA_DeliveryAddress).toISOString() : null }},
    {{ ui.form3.value.Remarks ?? '' }},
    {{ ui.form3.value.DeliveryAddress ?? '' }},
    {{ ui.form3.value.ATA_Terminal_Inland ? moment(ui.form3.value.ATA_Terminal_Inland).toISOString() : null }},
    {{ ui.form3.value.Containerverfuegbarkeit ? moment(ui.form3.value.Containerverfuegbarkeit).toISOString() : null }},
    {{ ui.form3.value.Transport_Mode_final_DeliveryAddress ?? '' }},
    {{ ui.form3.value.Direct_Truck ?? '' }},
    {{ ui.form3.value.to_Transporter ?? 0 }},
    {{ moment().utcOffset(0, true).toISOString() }},
    'Transport_Clone'
);
