 WHERE
 (Status_Transport LIKE '%' + ? + '%' OR ? = '')
AND (TransmissionTimestamp LIKE '%' + ? + '%' OR ? = '')
AND (Voyage LIKE '%' + ? + '%' OR ? = '')
AND (ContainerSize LIKE '%' + ? + '%' OR ? = '')
AND (Broker LIKE '%' + ? + '%' OR ? = '')
AND (Carrier LIKE '%' + ? + '%' OR ? = '')
AND (Vessel LIKE '%' + ? + '%' OR ? = '')
AND (PortOfDischarge_Lima LIKE '%' + ? + '%' OR ? = '')
AND (ETA_PortOfDischarge LIKE '%' + ? + '%' OR ? = '')
AND (PackingMethod LIKE '%' + ? + '%' OR ? = '')
AND (TotalWeight LIKE '%' + ? + '%' OR ? = '')
AND (AdvertFlag LIKE '%' + ? + '%' OR ? = '')
AND (RealAdvertFlag LIKE '%' + ? + '%' OR ? = '')
AND (EarliestAdvertDate LIKE '%' + ? + '%' OR ? = '')
AND (EarliestRealAdvertDate LIKE '%' + ? + '%' OR ? = '')
AND (todo LIKE '%' + ? + '%' OR ? = '')
AND (last_eventID LIKE '%' + ? + '%' OR ? = '')
AND (PortOfLoading_Lima LIKE '%' + ? + '%' OR ? = '')
AND (ETD_PortOfLoading LIKE '%' + ? + '%' OR ? = '')
AND (ETA_Terminal_Inland LIKE '%' + ? + '%' OR ? = '')
AND (DeliveryAddress LIKE '%' + ? + '%' OR ? = '')
AND (ETA_DeliveryAddress LIKE '%' + ? + '%' OR ? = '')
AND (Transport_Mode_Terminal LIKE '%' + ? + '%' OR ? = '')
AND (Transport_Mode_final_DeliveryAddress LIKE '%' + ? + '%' OR ? = '')
AND (ATA_DeliveryAddress LIKE '%' + ? + '%' OR ? = '')
AND (transport_Dispo_ID LIKE '%' + ? + '%' OR ? = '')
AND (Condition LIKE '%' + ? + '%' OR ? = '')
AND (into_CW1 LIKE '%' + ? + '%' OR ? = '')
AND (to_Customer LIKE '%' + ? + '%' OR ? = '')
AND (to_Transporter LIKE '%' + ? + '%' OR ? = '')
AND (DropOff_Terminal LIKE '%' + ? + '%' OR ? = '')
AND (Terminal_PortOfDischarge LIKE '%' + ? + '%' OR ? = '')
AND (ATA_Terminal_Inland LIKE '%' + ? + '%' OR ? = '')
AND (ATD_Terminal_Inland LIKE '%' + ? + '%' OR ? = '')
AND (ETA_Seaport LIKE '%' + ? + '%' OR ? = '')
AND (final_date_delivery_address LIKE '%' + ? + '%' OR ? = '')
AND (ctv_booking_id LIKE '%' + ? + '%' OR ? = '')
AND (CTV_ETA_PortOfDischarge LIKE '%' + ? + '%' OR ? = '')
AND (PortOfDischarge_UNLOCO LIKE '%' + ? + '%' OR ? = '')
AND (PortOfLoading_UNLOCO LIKE '%' + ? + '%' OR ? = '')
AND (ATA_DropOff_Terminal LIKE '%' + ? + '%' OR ? = '')
AND (DeliveryAddress_CTV LIKE '%' + ? + '%' OR ? = '')
AND (PortOfDischarge_UNLOCO_CTV LIKE '%' + ? + '%' OR ? = '')
AND (Carrier_CTV LIKE '%' + ? + '%' OR ? = '')
AND (customs_document_type LIKE '%' + ? + '%' OR ? = '')
AND (Terminal_Inland_CTV LIKE '%' + ? + '%' OR ? = '')
AND (ETD_Pickup_PortOfDischarge LIKE '%' + ? + '%' OR ? = '')
AND (pinState LIKE '%' + ? + '%' OR ? = '')
AND (nationalTransportState LIKE '%' + ? + '%' OR ? = '')
AND (finalDeliveryState LIKE '%' + ? + '%' OR ? = '')
AND (emptyReturnState LIKE '%' + ? + '%' OR ? = '')
AND (DeliveryInfo_send_to_CTV LIKE '%' + ? + '%' OR ? = '')
AND ([new] LIKE '%' + ? + '%' OR ? = '')
AND (Terminal_Inland_CundA LIKE '%' + ? + '%' OR ? = '')
AND (Direct_Truck LIKE '%' + ? + '%' OR ? = '')
AND (EventType LIKE '%' + ? + '%' OR ? = '')
AND (Transport_To_Terminal LIKE '%' + ? + '%' OR ? = '')
AND (Transport_Document_Number LIKE '%' + ? + '%' OR ? = '')
AND (Seal_Number LIKE '%' + ? + '%' OR ? = '')
AND (ETA_Deliveryadress_CTV LIKE '%' + ? + '%' OR ? = '')
AND (tm.Wert LIKE '%' + ? + '%' OR ? = '')
AND (tm2.Wert LIKE '%' + ? + '%' OR ? = '')


 ORDER BY
d.TransmissionTimestamp


OFFSET @Offset ROWS
FETCH NEXT @PageSize ROWS ONLY;